# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: chess_dev
      POSTGRES_USER: chess
      POSTGRES_PASSWORD: chesspw
    ports:
      - 5430:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
